apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "name" . }}
spec:
  replicas: 1
  serviceName: {{  template "name" . }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
    spec:
      containers:
        - name: rcon-web
          image: {{ template "image" . }}
          volumeMounts:
            - name: data
              mountPath: "/opt/rcon-web-admin/db"
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
            {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ template "pvc" . }}
